# configs
editor nvim
shell fish

# shortcuts
map ctrl+shift+c edit_config_file

# style
background_opacity 0.9
tab_bar_edge bottom
hide_window_decorations no
tab_bar_style powerline

# cursor animation
cursor_trail 200
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2


# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME


# Fix nerd symbols
include font-nerd-symbols.conf
